// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20240904042348_SeedRecipe")]
    partial class SeedRecipe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("API.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchQty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DyeingProcess")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MCNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkOrderNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YarnLotNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchNo = "Rafat",
                            BatchQty = "Rafat",
                            Date = "Rafat",
                            DyeingProcess = "Rafat",
                            FType = "Rafat",
                            MCNo = "Rafat",
                            Remarks = "Rafat",
                            WorkOrderNo = "Rafat",
                            YarnLotNo = "Rafat"
                        },
                        new
                        {
                            Id = 2,
                            BatchNo = "Rafat",
                            BatchQty = "Rafat",
                            Date = "Rafat",
                            DyeingProcess = "Rafat",
                            FType = "Rafat",
                            MCNo = "Rafat",
                            Remarks = "Rafat",
                            WorkOrderNo = "Rafat",
                            YarnLotNo = "Rafat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
